# -*- coding: utf-8 -*-
"""chap4 part 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15arrdfoyTEgGDhsHh4fDUkBuc_vig36q

# Original model
"""

from keras import models
from keras import layers

model = models.Sequential()
model.add(layers.Dense(16, activation = "relu", input_shape = (10000,)))
model.add(layers.Dense(16, activation  = "relu"))
model.add(layers.Dense(1, activation = "sigmoid"))

"""# Version of the model with lower capacity"""

model = models.Sequential()
model.add(layers.Dense(4, activation = "relu", input_shape = (10000,)))
model.add(layers.Dense(4, activation = "relu"))
model.add(layers.Dense(1, activation = "sigmoid"))

"""# Version of the model with higher capacity"""

model = models.Sequential()
model.add(layers.Dense(512, activation = "relu", input_shape = (10000,)))
model.add(layers.Dense(512, activation  = "relu"))
model.add(layers.Dense(1, activation = "sigmoid"))

"""# Adding L2 weight regularization to the model"""

from keras import regularizers

model = models.Sequential()
model.add(layers.Dense(16, kernel_regularizer=regularizers.l2(0.001),
                       activation = "relu", input_shape = (10000,)))
model.add(layers.Dense(16, kernel_regularizer=regularizers.l2(0.001),
                       activation = "relu"))
model.add(layers.Dense(1, activation = "sigmoid"))

"""# Different weight regularizers available in keras"""

from keras import regularizers

regularizers.l1(0.001)

regularizers.l1_l2(l1 = 0.001, l2 = 0.001)

"""# Adding dropout to the IMBD network"""

model = models.Sequential()
model.add(layers.Dense(16, activation = "relu", input_shape = (10000,)))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(16, activation = "relu"))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(1, activation = "sigmoid"))

